//Each new term in the Fibonacci sequence is generated by adding the previous
//two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million
// find the sum of the even-valued terms.

const fibonacci = (param) => {
    let fibonacci = (param-1) + (param-2) 

    let num = 10

    let arr = []

    for(let i = 0; i < num; i++ ){
        if(i%2===0){
            arr = arr + i
        }
    }
    return fibonacci
}

module.exports = fibonacci